[project]
name = 'stacks-fund'
description = 'Bitcoin-Native Community Funding & Governance on Stacks L2'
authors = []
telemetry = true
cache_dir = './.cache'
requirements = []

[contracts.voting]
path = 'contracts/voting.clar'
clarity_version = 4
epoch = '3.3'

[contracts.crowdfunding-campaign]
path = 'contracts/crowdfunding-campaign.clar'
clarity_version = 4
epoch = '3.3'

[contracts.milestone-tracker]
path = 'contracts/milestone-tracker.clar'
clarity_version = 4
epoch = '3.3'

[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false

[repl.remote_data]
enabled = false
api_url = 'https://api.hiro.so'
